### ISSUE TITLE
Wartungsmodus

### ISSUE THREAD

**Issue by Mynyx** [contao/docs#269]
Der Wartungsmodus ist im Handbuch nicht dokumentiert.

**Comment by fritzmg** [comment]
@Mynyx can you provide a PR? You only need to provide it in one language (English or German).

**Comment by fkaminski** [comment]
@Mynyx - Have you already prepared something for this?
Otherwise we can take the appropriate information from this manual:
https://community.contao.org/de/showthread.php?77280-Anpassung-Wartungsmodus-4-9

@fritzmg 
The above info also deals with the translation.
Should we separate this beforehand. On the other hand, the procedure is already described in the developer documentation ...

**Comment by netzarbeiter** [comment]
The maintenance mode has been rewritten in Contao 4.13 and has also found its way into the doku with the release.

- https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-konfigurieren/#website-einstellungen
- https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-als-zentrale-elemente/#seitentypen
- https://docs.contao.org/manual/de/anleitungen/wartungstemplate-anpassen/
