### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by dmolineus** [contao/docs#443]
When I use search engines I often get results from the former documentations. I'd like to discuss how it can be improved so that (new) user find information at the new documentation:

 - Take old documentation offline and provide redirects where possible
 - Add a note at the header of the old docs to inform that a new documentation exists

**Comment by fritzmg** [comment]
We deliberately left the old documentation online, so that we can see if some essentials are still missing and which URLs can be redirected. We will leave the old docs online for the remainder of the year for this purpose. 

A lot of redirects have already been implemented. You can report URLs that can be redirected to the new manual or dev docs :).

**Comment by dmolineus** [comment]
Yeah I guessed that. So adding a notification on the header would be great.

**Comment by fritzmg** [comment]
I have now redirected everything else. However, the [archived GitHub Repository](https://github.com/contao/docs-archive) might still show up in search results.
