### ISSUE TITLE
Nicht nachvollziehbare Ergebnisse der Suchfunktion 

### ISSUE THREAD

**Issue by Mynyx** [contao/docs#83]
Die Suchfunktion zeigt nicht nachvollziehbare Ergebnisse an, beispielsweise zum Suchbegriff "cache" die Seite "Contao im Schnelldurchlauf", die den Begriff "cache" nicht enthält.

![image](https://user-images.githubusercontent.com/1632642/66816844-0e16e080-ef3b-11e9-88ed-53081024dce5.png)

**Comment by fritzmg** [comment]
This is because the Learn Theme by default also does a "fuzzy" search where up to two characters can be added, removed or transposed for a match to occur. This allows you to see matches even if you don't type the word exactly - which is mostly useful for more complicated words. Though obviously it will lead to more false positives, the shorter the word is.

However, exact matches are always ranked much higher than the fuzzy matches and thus will appear first in the search results. The ranking goes like this:

1. exact match: ranked up by a factor of **100**
2. wild card matches: factor **10**
3. fuzzy match: factor **1**

In any case, as this is done in the core `search.js` and I don't really want to override it just for our purposes, I am going to close this. If you think it should be changed regardless, may be open a ticket in the GitHub repository of the theme itself: https://github.com/matcornic/hugo-theme-learn/issues May be it can be improved in some other way.
