### ISSUE TITLE
Adjustments for "Installing Test Version" necessary

### ISSUE THREAD

**Issue by fkaminski** [contao/docs#902]
Not sure, but I think (at least) [the examples for installing a development version](https://docs.contao.org/manual/en/guides/install-test-versions/#installing-developer-versions) are no longer correct.

Tried to get a (4.13.x) development version locally via the CM. 
According to the current examples (`4.9.x-dev`) I had tried with `4.13.x-dev`. Has turned out that here the specification `4.x-dev` is necessary.

**Comment by fritzmg** [comment]
That's because there is no release of Contao 4.13 yet (RC or otherwise). If you want to install the currently developing feature or major version, then it would be `4.x-dev`, yes. Or `5.x-dev` after 4.13 is released. This might change though as there was discussion about changing the default branch name again recently.

**Comment by fkaminski** [comment]
Understood. Nevertheless, at least as of today, the examples for the development installation would be misleading.

**Comment by fkaminski** [comment]
see #978
